### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wenLiangcan** [WeijuNB/PyF5#13]
```
 % f5                                                                           
Traceback (most recent call last):
  File "/usr/bin/f5", line 11, in <module>
    server = F5Server()
  File "/usr/lib/python2.7/site-packages/pyf5/server.py", line 135, in __init__
    Application.__init__(self, handlers, default_host, transforms, wsgi, **settings)
TypeError: __init__() takes at most 4 arguments (6 given)
```

**Comment by lucheng-wh** [comment]
@wenLiangcan 
碰到相同的问题，Application.**init**(self, handlers, default_host, transforms, wsgi, **settings) 
参数过多，去掉default_host, transforms, wsg 即可
